### ISSUE TITLE
Bedrock players cannot sit when using geyser

### ISSUE THREAD

**Issue by DDAN-17** [UsainSrht/Sit#6]
When joining a server using geyser, bedrock players cannot use chairs, because the pigs don't exist until you try to click on them. To counteract this, I recommend creating a new config option for the pigs to always exist.

**Comment by UsainSrht** [comment]
Can you elaborate? Are you suggesting that we spawn a pig for each stair?

**Comment by DDAN-17** [comment]
Yes, and maybe despawn it if there aren't players in a certain radius.

**Comment by UsainSrht** [comment]
That would be very inefficent. I'll see what i can do for bedrock players.

**Comment by DDAN-17** [comment]
Nevermind, I don't know why it didn't work before, but it does now.
