### ISSUE TITLE
how to fix that? 

### ISSUE THREAD

**Issue by zevazee1** [UsainSrht/Sit#8]
![image](https://github.com/user-attachments/assets/0bf21d96-16df-49d5-bf87-ef842cca80cd)
it happened after editing saddle to false in config. but it only happense when old stair on which player was sitting is broken

**Comment by UsainSrht** [comment]
Breaking the block someone is sitting on shouldn't be a problem.

Can you provide more details?

- did you change saddle option while someone is sitting?
- your server and plugin version

**Comment by zevazee1** [comment]
sorry for disturbing, i`ve already fixed that. it was one to million chance. i edited config while i was sitting on stair, and after restart of the server i stood up and that happened. i ujst killed that entity

**Comment by UsainSrht** [comment]
alright then
