### ISSUE TITLE
Invisible Pig Situation

### ISSUE THREAD

**Issue by herbthyme** [UsainSrht/Sit#9]
Using this plugin on a server, I logged off while sitting down. Unsure if this is related, but the server likely had a couple restarts in the time I was away. I've logged back in, and there is now an invisible pig in the location where I was sitting that I cannot get rid of. Conventional means of killing it AND commands both have had no effect, and it's obstructing part of a structure I've been building. Is there any specific way to rid this invisible pig from existence?

**Comment by laurianepop2008** [comment]
Did you found a solution? I have the same bug on my server

**Comment by herbthyme** [comment]
> Did you found a solution? I have the same bug on my server

Actually, yes! For whatever reason, I came back later and I was able to kill it in creative mode by regularly attacking it. By no means is this a permanent resolution to the issue, but it'll fix it for the time being.

**Comment by UsainSrht** [comment]
fixed with 148ffa - sit entities will not be saved if server stops

you should be able to remove the existing invisible pig with /kill command try `/kill @e[type=pig,distance=..5]` within 5 blocks of that pig.

**Comment by herbthyme** [comment]
> you should be able to remove the existing invisible pig with /kill command try `/kill @e[type=pig,distance=..5]` within 5 blocks of that pig.

I had already tried that exact command and a few iterations of it, and it didn't want to work at all...

**Comment by laurianepop2008** [comment]
Thats wierd thanks for letting me know

**Comment by UsainSrht** [comment]
> > you should be able to remove the existing invisible pig with /kill command try `/kill @e[type=pig,distance=..5]` within 5 blocks of that pig.
> 
> I had already tried that exact command and a few iterations of it, and it didn't want to work at all...

just tried it and it worked

here's the fixed version https://modrinth.com/plugin/stairsit/version/1.7.1

thank you for reporting. Enjoy!
